### ISSUE TITLE
What is your GWO optimizing?

### ISSUE THREAD

**Issue by JiaQiMark** [BatchClayderman/CEEMDAN-SE-GWO-LSTM#1]
Please! Please! Please!
I have read your paper and your code, but I still could not understand what your GWO optimized.
Do you GWO optimize the Weight parameters of LSTM or the hyperparameter of LSTM? Neither seem to be

Your paper indicates that you danamically updated the hyperparameter of LSTM, but in your code the hyperparameter is given in advance and unmodifiable, just like [12, 64, 64, 1] in your code.

**Comment by yueryang** [comment]
Thanks for your question. 
This paper mainly focuses on combining CEEMDAN, SE, GWO, and LSTM together and proves that the combination model can work well. The GWO is used to provide an optimization direction of LSTM. If you want to know more about the paper in theory, please contact the first author. 
For the codes written in our published codes in Github, we only provide an example (or a group of parameters) to show how GWO can optimize LSTM. We will not publish the complete codes as we run the codes separately in different cases and datasets with different (groups of) parameters. And I do not think that readers will like to see plenty of codes with lots of similar parts. Before you run, you just need to adjust the parameters yourself to suit your datasets. 
I hope that my answers can be useful to you.

**Comment by JiaQiMark** [comment]
Thanks for your answer.
Did your GWO optimize the hyperparameter, such as the length of sequence, the hidden size of layer1, the hidden size of layer2?

**Comment by yueryang** [comment]
This question seems theoretical. As I just contributed to the implementation of the sample codes and the LaTeX typesetting, please contact the first author for the design of the detailed methods. If you have further questions, please feel free to contact me.

**Comment by JiaQiMark** [comment]
OK, thank you very much

**Comment by yueryang** [comment]
You are welcome. I will close this issue.
